#!/usr/bin/env python3.12
"""
Build data/history.js — 5 years of monthly closes + last-10-day sparkline +
this-week OHLC read for every stock in fundamentals.json plus NIFTY.
Feeds the dashboard's investment calculator and weekly chart analysis.
"""
import json
from pathlib import Path

import yfinance as yf

ROOT = Path(__file__).resolve().parent.parent
FUND = ROOT / "data" / "fundamentals.json"
OUT = ROOT / "data" / "history.js"
NIFTY = "^NSEI"

symbols = [s["symbol"] for s in json.loads(FUND.read_text())["stocks"]] + [NIFTY]
hist = {}
for s in symbols:
    ticker = s if s.startswith("^") else s + ".NS"
    try:
        t = yf.Ticker(ticker)
        mo = t.history(period="5y", interval="1mo", auto_adjust=True)["Close"].dropna()
        monthly = [[idx.strftime("%Y-%m"), round(float(v), 1)] for idx, v in mo.items()]
        dl = t.history(period="1mo", interval="1d", auto_adjust=True)
        d = dl["Close"].dropna()
        daily10 = [round(float(v), 1) for v in d.tail(10)]
        # this trading week = last 5 sessions
        wk = dl.tail(5)
        week = {
            "open": round(float(wk["Open"].iloc[0]), 1),
            "high": round(float(wk["High"].max()), 1),
            "low": round(float(wk["Low"].min()), 1),
            "close": round(float(wk["Close"].iloc[-1]), 1),
            "chg_pct": round((float(wk["Close"].iloc[-1]) / float(wk["Close"].iloc[0]) - 1) * 100, 2)
                        if len(wk) > 1 else 0.0,
            "vol_vs_prior": round(float(wk["Volume"].mean()) /
                                  max(1.0, float(dl["Volume"].head(max(1, len(dl) - 5)).mean())), 2)
                        if "Volume" in dl and len(dl) > 6 else None,
        }
        hist[s] = {"monthly": monthly, "daily10": daily10, "week": week}
        print(f"  {s}: {len(monthly)} months, week {week['chg_pct']}%")
    except Exception as e:
        print(f"  ! {s}: {e}")

OUT.write_text("// generated by scripts/build_history.py\nwindow.HISTORY = " +
               json.dumps(hist) + ";\n")
print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
